CREATE TABLE patient
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    surname        VARCHAR(255),
    passportid     VARCHAR(255),
    birth_date     date,
    address        VARCHAR(255),
    travel_voucher SMALLINT,
    CONSTRAINT pk_patient PRIMARY KEY (id)
);

CREATE TABLE period
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id     BIGINT                                  NOT NULL,
    admission_date date,
    discharge_date date,
    CONSTRAINT pk_period PRIMARY KEY (id)
);

ALTER TABLE period
    ADD CONSTRAINT FK_PERIOD_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);