CREATE TABLE medicine
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    quantity INTEGER                                 NOT NULL,
    price    DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_medicine PRIMARY KEY (id)
);

CREATE TABLE medicine_patient_stay_period
(
    medicine_id            BIGINT NOT NULL,
    patient_stay_period_id BIGINT NOT NULL,
    CONSTRAINT pk_medicine_patientstayperiod PRIMARY KEY (medicine_id, patient_stay_period_id)
);

ALTER TABLE medicine_patient_stay_period
    ADD CONSTRAINT fk_medpatstaper_on_medicine FOREIGN KEY (medicine_id) REFERENCES medicine (id);

ALTER TABLE medicine_patient_stay_period
    ADD CONSTRAINT fk_medpatstaper_on_patient_stay_period FOREIGN KEY (patient_stay_period_id) REFERENCES period (id);