CREATE TABLE prescription
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    medicine_id       BIGINT,
    stay_period_id    BIGINT,
    assigned_quantity INTEGER                                 NOT NULL,
    CONSTRAINT pk_prescription PRIMARY KEY (id)
);

ALTER TABLE prescription
    ADD CONSTRAINT FK_PRESCRIPTION_ON_MEDICINE FOREIGN KEY (medicine_id) REFERENCES medicine (id);

ALTER TABLE prescription
    ADD CONSTRAINT FK_PRESCRIPTION_ON_STAY_PERIOD FOREIGN KEY (stay_period_id) REFERENCES period (id);

DROP TABLE medicine_patient_stay_period;